### ISSUE TITLE
Bug Fix Package Manager

### ISSUE THREAD

**Issue by ViniciusDeep** [ViniciusDeep/CBuilder#12]
<img width="733" alt="Screen Shot 2019-10-05 at 18 14 46" src="https://user-images.githubusercontent.com/32227073/66261000-990a1500-e79c-11e9-842d-e7f855d26241.png">

**Comment by mike011** [comment]
@ViniciusDeep You can see from the above that it checked out 0.1.0, the code tagged at this version doesn't have the Package.swift file. Just create a new tag and you should be good to go.
